version: '3'
services:
  nginx:
    build:
      context: ./
      dockerfile: build/dev/nginx/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - 80:80
    depends_on:
      - php-fpm
      - postgres
  php-fpm:
    build:
      context: ./
      dockerfile: build/dev/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
  php-cli:
    build:
      context: ./
      dockerfile: build/dev/php-cli/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
  postgres:
    build:
      context: ./
      dockerfile: build/prod/postgres/Dockerfile
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432

volumes:
  postgres:

networks:
  gis_network_dev: