version: '3'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - 80:80
    depends_on:
      - php-fpm
      - postgres
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
  composer:
    image: composer
    volumes:
      - ./:/app
    command: install
  postgres:
    image: postgres:11.5
    volumes:
      - ./docker/database/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432

volumes:
    postgres:

networks:
  gis_network: